services:
  m1:
    build:
      context: dimgoA
      args:
        - IARCH=${IARCH}
        - EAVER=${EAVER}
        - agentRpm=${agentRpm}
        - mmsGroupId=${mmsGroupId}
        - mmsApiKey=${mmsApiKey}
        - mmsBaseUrl=${mmsBaseUrl}
        - httpProxy=${httpProxy}
    image: ${IARCH}/mongodb${EAVER}:oa
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2048M
    container_name: m1
    hostname: m1
    privileged: true
    platform: linux/${PARCH:-arm64}
    environment:
      - TZ=Asia/Seoul
      - RSNAME=${RSNAME}
    volumes:
      - week1_docker_m1:/data
    ulimits:
      nofile: 64000
      nproc: 64000
      cpu: -1
      as: -1
      memlock: -1
      fsize: -1

  m2:
    depends_on:
      - m1
    image: ${IARCH}/mongodb${EAVER}:oa
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2048M
    container_name: m2
    hostname: m2
    privileged: true
    platform: linux/${PARCH:-arm64}
    environment:
      - TZ=Asia/Seoul
    volumes:
      - week1_docker_m2:/data
    ulimits:
      nofile: 64000
      nproc: 64000
      cpu: -1
      as: -1
      memlock: -1
      fsize: -1

  m3:
    depends_on:
      - m1
    image: ${IARCH}/mongodb${EAVER}:oa
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2048M
    container_name: m3
    hostname: m3
    privileged: true
    platform: linux/${PARCH:-arm64}
    environment:
      - TZ=Asia/Seoul
    volumes:
      - week1_docker_m3:/data
    ulimits:
      nofile: 64000
      nproc: 64000
      cpu: -1
      as: -1
      memlock: -1
      fsize: -1

networks:
  default:
    name: mdb_net
    external: true

volumes:
  week1_docker_m1:
    external: true
  week1_docker_m2:
    external: true
  week1_docker_m3:
    external: true
