services:
  on:
    build:
      context: dimgoN
      args:
        - IARCH=${IARCH}
        - EAVER=${EAVER}
        - RSNAME=${RSNAME}
    image: ${IARCH}/mongodb${EAVER}:on
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 6G
    container_name: on
    hostname: on
    ports:
      - "80:80"
    privileged: true
    platform: linux/${PARCH:-arm64}
    environment:
      - TZ=Asia/Seoul
      - RSNAME=${RSNAME}
    volumes:
      - on:/data
      - ./provision:/var/lib/mongo/start
      - ../week1_docker/start/create1stUser.js:/var/lib/mongo/start/create1stUser.js
      - ../week1_docker/start/createUsers.js:/var/lib/mongo/start/createUsers.js
    ulimits:
      nofile: 64000
      nproc: 64000
      cpu: -1
      as: -1
      memlock: -1
      fsize: -1

  o2:
    build:
      context: dimgoM
      args:
        - IARCH=${IARCH}
        - EAVER=${EAVER}
        - RSNAME=${RSNAME}
        - omdbusr=${omdbusr}
        - omdbpwd=${omdbpwd}
        - omCentralUrl=${omCentralUrl}
    image: ${IARCH}/mongodb${EAVER}:om
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 12G
    container_name: o2
    hostname: o2
    ports:
      - "8082:8080"
    privileged: true
    platform: linux/${PARCH:-arm64}
    environment:
      - TZ=Asia/Seoul
    volumes:
      - o2:/data
      - ./provision:/var/lib/mongo/start
    ulimits:
      nofile: 64000
      nproc: 64000
      cpu: -1
      as: -1
      memlock: -1
      fsize: -1

  o3:
    build:
      context: dimgoB
      args:
        - IARCH=${IARCH}
        - EAVER=${EAVER}
        - RSNAME=${RSNAME}
    image: ${IARCH}/mongodb${EAVER}:ob
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 12G
    container_name: o3
    hostname: o3
    ports:
      - "8083:8080"
    privileged: true
    platform: linux/${PARCH:-arm64}
    environment:
      - TZ=Asia/Seoul
    volumes:
      - o3:/data
      - ./provision:/var/lib/mongo/start
    ulimits:
      nofile: 64000
      nproc: 64000
      cpu: -1
      as: -1
      memlock: -1
      fsize: -1

networks:
  default:
    name: mdb_net
    external: true

volumes:
  on:
  o2:
  o3:
