---
replSetName: sccamp

superUser: root
superPwd: root1234

superUserScript: |
  admin = db.getSiblingDB("admin")
  admin.createUser({
    user: "root",
    pwd: "root1234",
    roles: [ { role: "root", db: "admin" } ]
  })

adminUser: admin
adminPwd: admin1234

UsersScript: |
  admin = db.getSiblingDB("admin")
  admin.createUser({
    user: "admin",
    pwd: "admin1234",
    roles: [
      { role: "userAdminAnyDatabase", db: "admin" },
      { role: "dbAdminAnyDatabase", db: "admin" },
      { role: "clusterAdmin", db: "admin" },
    ]
  })
  admin.createUser({
    user: "pm",
    pwd: "pm1234",
    roles: [
      { role: "clusterAdmin", db: "admin" },
      { role: "dbAdminAnyDatabase", db: "admin" },
      { role: "readWriteAnyDatabase", db: "admin" }
    ]
  })
